Matrix Calculator (NumPy)

In [1]:
import numpy as np

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Addition
print("\nAddition:\n", A + B)

# Subtraction
print("\nSubtraction:\n", A - B)

# Multiplication (element-wise)
print("\nElement-wise Multiplication:\n", A * B)

# Matrix multiplication
print("\nMatrix Multiplication:\n", np.dot(A, B))

# Transpose
print("\nTranspose of A:\n", A.T)

# Determinant
print("\nDeterminant of A:", np.linalg.det(A))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.0000000000000004
