Random Data Simulator

In [1]:
import numpy as np

# Generate random data
data = np.random.randint(50, 100, size=(5, 3))

print("Random Student Data:\n", data)

# Mean
print("Mean:", np.mean(data))

# Standard deviation
print("Std Dev:", np.std(data))

# Min & Max
print("Min:", np.min(data))
print("Max:", np.max(data))

# Normalize data (broadcasting)
normalized = (data - np.mean(data)) / np.std(data)
print("\nNormalized Data:\n", normalized)

Random Student Data:
 [[84 53 74]
 [76 70 51]
 [60 59 78]
 [63 60 98]
 [82 94 74]]
Mean: 71.73333333333333
Std Dev: 13.679506163925982
Min: 51
Max: 98

Normalized Data:
 [[ 0.89671853 -1.36944515  0.16569799]
 [ 0.3119021  -0.12671023 -1.51564926]
 [-0.85773077 -0.93083282  0.45810621]
 [-0.63842461 -0.85773077  1.92014729]
 [ 0.75051442  1.62773907  0.16569799]]


🧠 What is Data Normalization?

👉 Normalization = scaling data to a standard range

It makes values comparable and balanced.

z = (x−μ)​/σ 

x = value
μ = mean
σ = standard deviation

