Student Data Analyzer

In [9]:
# Import numpy for numerical operations
import numpy as np  

# Create a 2D array: 4 students x 3 subjects (marks ranging from 50-95)
marks = np.array([
    [80, 75, 90],
    [60, 65, 70],
    [85, 90, 95],
    [50, 55, 60]
])

print("Marks of students:", marks)

# Calculate average marks for each student across all subjects
avg_marks = marks.mean(axis=1)
print("Average marks of each student:", avg_marks)

# Calculate average marks for each subject across all students
avg_subj = marks.mean(axis=0)
print("Average marks of each subject:", avg_subj)

# Find maximum marks in each subject
max_marks = marks.max(axis=0)
print("Maximum marks in each subject:", max_marks)

# Identify the index of the topper student (highest average marks)
topper = avg_marks.argmax()
print("Index of the topper student:", topper)

# Add 5 bonus marks to all student marks
bouns_marks = marks + 5
print("Marks after adding bonus:", bouns_marks)

# Check which students passed (average marks >= 60) - returns boolean array
passed = avg_marks >= 60
print("Students who passed:", passed)


Marks of students: [[80 75 90]
 [60 65 70]
 [85 90 95]
 [50 55 60]]
Average marks of each student: [81.66666667 65.         90.         55.        ]
Average marks of each subject: [68.75 71.25 78.75]
Maximum marks in each subject: [85 90 95]
Index of the topper student: 2
Marks after adding bonus: [[ 85  80  95]
 [ 65  70  75]
 [ 90  95 100]
 [ 55  60  65]]
Students who passed: [ True  True  True False]
