Importing Numpy Library


In [2]:
import numpy as np

Creating 1Dimensional numpy array

In [3]:
array1 = np.array(([1,2,3,4,5]))
print(array1)

[1 2 3 4 5]


Creating 2Dimensional numpy array

In [4]:
array2 = np.array(([0, 1, 2, 3, 4], [5,6,7,8,9]))
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Creating 3Dimensional numpy array

In [5]:
array3 = np.array((([1,2,3], [4,5,6]) , ([7,8,9], [10,11,12])))
print(array3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Indexing


1D arrays

In [6]:
array1 = np.array(([1,2,3,4,5]))
print(array1[3])
print(array1[0:3])
print(array1[-3])

4
[1 2 3]
3
