Importing Numpy Library


In [ ]:
# Import the NumPy library for numerical operations
import numpy as np

Creating 1Dimensional numpy array

In [ ]:
# Create a 1D array with elements 1 to 5
array1 = np.array([1,2,3,4,5])
# Display the array
print(array1)

[1 2 3 4 5]


Creating 2Dimensional numpy array

In [ ]:
# Create a 2D array with two rows
array2 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
# Display the 2D array
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Creating 3Dimensional numpy array

In [ ]:
# Create a 3D array with two 2D arrays
array3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
# Display the 3D array
print(array3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Redefine array1 for indexing demonstration
array1 = np.array([1,2,3,4,5])
# Access element at index 3 (fourth element, since indexing starts at 0)
print(array1[3])
# Slice the array from index 0 to 3 (exclusive)
print(array1[0:3])
# Access the third last element
print(array1[-3])

4
[1 2 3]
3


INDEXING IN NUMPY


Indexing in 1D Array

Write a Python program to access elements of a 1D NumPy array using indexing.

In [ ]:
# Import NumPy library
import numpy as np  
# Create a 1D array for indexing examples
arr1 = np.array([1,2,3,4,5])
# Print the original array
print("Original array:", arr1)
# Access and print element at index 1 (second element)
print("Element at index 1:", arr1[1])
# Access and print element at index 0 (first element)
print("Element at index 0:", arr1[0])
# Access and print the last element using negative indexing
print("Last element:", arr1[-1])

Original array: [1 2 3 4 5]
Element at index 1: 2
Element at index 0: 1
Last element: 5


Indexing in 2D Array

Write a Python program to access elements of a 2D NumPy array using indexing.

In [ ]:
# Import NumPy library
import numpy as np
# Create a 2D array for indexing examples
arr2 = np.array([[1,2,3,4,5], [5,6,7,8,9]])
# Print the original 2D array
print("Original array:\n", arr2)
# Access element at row 0, column 2
print("Element at index [0][2]:", arr2[0][2])
# Access element at row 1, column 4
print("Element at index [1][4]:", arr2[1][4])
# Access last element of the first row using negative indexing
print("Last element of the first row:", arr2[0][-1])

Original array:
 [[1 2 3 4 5]
 [5 6 7 8 9]]
Element at index [0][2]: 3
Element at index [1][4]: 9
Last element of the first row: 5


Indexing in 3D Array

Write a Python program to access elements of a 3D NumPy array using indexing.

In [ ]:
# Import NumPy library
import numpy as np
# Create a 3D array for indexing examples
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [1,3,6]]])
# Print the original 3D array
print("Original array:\n", arr3)
# Access element at depth 0, row 1, column 2
print("Element at index [0][1][2]:", arr3[0][1][2])
# Access element at depth 1, row 0, column 1
print("Element at index [1][0][1]:", arr3[1][0][1])
# Access last element of the second row of the first 2D array
print("Last element of the second row of the first 2D array:", arr3[0][1][-1])

Original array:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 3 6]]]
Element at index [0][1][2]: 6
Element at index [1][0][1]: 8
Last element of the second row of the first 2D array: 6
