Importing Numpy Library


In [ ]:
# Import the NumPy library for numerical operations
import numpy as np

Creating 1Dimensional numpy array

In [ ]:
# Create a 1D array with elements 1 to 5
array1 = np.array([1,2,3,4,5])
# Display the array
print(array1)

[1 2 3 4 5]


Creating 2Dimensional numpy array

In [ ]:
# Create a 2D array with two rows
array2 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
# Display the 2D array
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Creating 3Dimensional numpy array

In [ ]:
# Create a 3D array with two 2D arrays
array3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
# Display the 3D array
print(array3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Redefine array1 for indexing demonstration
array1 = np.array([1,2,3,4,5])
# Access element at index 3 (fourth element, since indexing starts at 0)
print(array1[3])
# Slice the array from index 0 to 3 (exclusive)
print(array1[0:3])
# Access the third last element
print(array1[-3])

4
[1 2 3]
3


INDEXING IN NUMPY


Indexing in 1D Array

Write a Python program to access elements of a 1D NumPy array using indexing.

In [ ]:
# Import NumPy library
import numpy as np  
# Create a 1D array for indexing examples
arr1 = np.array([1,2,3,4,5])
# Print the original array
print("Original array:", arr1)
# Access and print element at index 1 (second element)
print("Element at index 1:", arr1[1])
# Access and print element at index 0 (first element)
print("Element at index 0:", arr1[0])
# Access and print the last element using negative indexing
print("Last element:", arr1[-1])

Original array: [1 2 3 4 5]
Element at index 1: 2
Element at index 0: 1
Last element: 5


Indexing in 2D Array

Write a Python program to access elements of a 2D NumPy array using indexing.

In [ ]:
# Import NumPy library
import numpy as np
# Create a 2D array for indexing examples
arr2 = np.array([[1,2,3,4,5], [5,6,7,8,9]])
# Print the original 2D array
print("Original array:\n", arr2)
# Access element at row 0, column 2
print("Element at index [0][2]:", arr2[0][2])
# Access element at row 1, column 4
print("Element at index [1][4]:", arr2[1][4])
# Access last element of the first row using negative indexing
print("Last element of the first row:", arr2[0][-1])

Original array:
 [[1 2 3 4 5]
 [5 6 7 8 9]]
Element at index [0][2]: 3
Element at index [1][4]: 9
Last element of the first row: 5


Indexing in 3D Array

Write a Python program to access elements of a 3D NumPy array using indexing.

In [ ]:
# Import NumPy library
import numpy as np
# Create a 3D array for indexing examples
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [1,3,6]]])
# Print the original 3D array
print("Original array:\n", arr3)
# Access element at depth 0, row 1, column 2
print("Element at index [0][1][2]:", arr3[0][1][2])
# Access element at depth 1, row 0, column 1
print("Element at index [1][0][1]:", arr3[1][0][1])
# Access last element of the second row of the first 2D array
print("Last element of the second row of the first 2D array:", arr3[0][1][-1])

Original array:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 3 6]]]
Element at index [0][1][2]: 6
Element at index [1][0][1]: 8
Last element of the second row of the first 2D array: 6


SLICING IN NUMPY


Slicing in 1D Array

Write a Python program to slice elements from a 1D NumPy array

In [12]:
import numpy as np
# Create a 1D array for slicing examples        
arr1 = np.array([1,2,3,4,5])
# Print the original array  
print("Original array:", arr1)
# Slice the array from index 0 to 3 (exclusive)
print("Sliced array (0:3):", arr1[0:3])
# Slice the array from index 2 to the end
print("Sliced array (2:):", arr1[2:])
# Slice the array from the beginning to index 3 (exclusive)
print("Sliced array (:3):", arr1[:3])
# Slice the array with a step of 2
print("Sliced array with step 2 (0:5:2):", arr1[0:5:2])

Original array: [1 2 3 4 5]
Sliced array (0:3): [1 2 3]
Sliced array (2:): [3 4 5]
Sliced array (:3): [1 2 3]
Sliced array with step 2 (0:5:2): [1 3 5]


 Slicing in 2D Array

Write a Python program to slice rows and columns from a 2D NumPy array.


In [ ]:
import numpy as np
# Create a 2D array for slicing examples
arr2 = np.array([[1,2,3,4,5], [5,6,7,8,9]])
# Print the original 2D array   
print("Original array:\n", arr2)
# Slice the first row (row index 0)
print("Sliced first row (0:1):\n", arr2[0:1])
# Slice the second row (row index 1)
print("Sliced second row (1:2):\n", arr2[1:2])
# Slice the first two columns of the first row
print("Sliced first two columns of the first row (0:1, 0:2):\n", arr2[0:1, 0:2])
# Slice the last three columns of the second row
print("Sliced last three columns of the second row (1:2, 2:5):\n", arr2[1:2, 2:5])


Original array:
 [[1 2 3 4 5]
 [5 6 7 8 9]]
Sliced first row (0:1):
 [[1 2 3 4 5]]
Sliced second row (1:2):
 [[5 6 7 8 9]]
Sliced first two columns of the first row (0:1, 0:2):
 [[1 2]]
Sliced last three columns of the second row (1:2, 2:5):
 [7]


 Slicing in 2D Array

Write a Python program to slice rows and columns from a 2D NumPy array.


In [15]:
import numpy as np
# Create a 3D array for slicing examples
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [1,3,6]]])
# Print the original 3D array
print("Original array:\n", arr3)
# Slice the first 2D array (depth index 0)
print("Sliced first 2D array (0:1):\n", arr3[0:1])
# Slice the second 2D array (depth index 1) 
print("Sliced second 2D array (1:2):\n", arr3[1:2])
# Slice the first row of the first 2D array
print("Sliced first row of the first 2D array (0:1, 0:1):\n", arr3[0:1, 0:1])
# Slice the second row of the second 2D array
print("Sliced second row of the second 2D array (1:2, 1:2):\n", arr3[1:2, 1:2])


Original array:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 3 6]]]
Sliced first 2D array (0:1):
 [[[1 2 3]
  [4 5 6]]]
Sliced second 2D array (1:2):
 [[[7 8 9]
  [1 3 6]]]
Sliced first row of the first 2D array (0:1, 0:1):
 [[[1 2 3]]]
Sliced second row of the second 2D array (1:2, 1:2):
 [[[1 3 6]]]


Mathematical Opreations

Create a 1D NumPy array and find max, min, sum, and mean, standard deviation

In [16]:
import numpy as np
# Create a 1D array for slicing examples    
arr1 = np.array([1,2,3,4,5])
# Print the original array
print("Original array:", arr1)
# Access and print the maximum value in the array
print("Maximum value in the array:", arr1.max())
# Access and print the minimum value in the array
print("Minimum value in the array:", arr1.min())
# Access and print the sum of all values in the array
print("Sum of all values in the array:", arr1.sum())
# Access and print the mean of all values in the array
print("Mean of all values in the array:", arr1.mean())
# Access and print the standard deviation of all values in the array
print("Standard deviation of all values in the array:", arr1.std())


Original array: [1 2 3 4 5]
Maximum value in the array: 5
Minimum value in the array: 1
Sum of all values in the array: 15
Mean of all values in the array: 3.0
Standard deviation of all values in the array: 1.4142135623730951


Create two 2D arrays and Perform addition, subtraction, multiplication, matrix multiplication, and division elementwise.

In [17]:
import numpy as np
# Create two 2D arrays for slicing examples
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
# Print the original arrays
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
# Perform element-wise addition of the two arrays   
print("Element-wise addition of arr1 and arr2:\n", arr1 + arr2)
# Perform element-wise multiplication of the two arrays
print("Element-wise multiplication of arr1 and arr2:\n", arr1 * arr2)
# Perform matrix multiplication of the two arrays   
print("Matrix multiplication of arr1 and arr2:\n", np.dot(arr1, arr2))
# perform element-wise division of the two arrays
print("Element-wise division of arr1 by arr2:\n", arr1 / arr2)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Element-wise addition of arr1 and arr2:
 [[ 6  8]
 [10 12]]
Element-wise multiplication of arr1 and arr2:
 [[ 5 12]
 [21 32]]
Matrix multiplication of arr1 and arr2:
 [[19 22]
 [43 50]]
Element-wise division of arr1 by arr2:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


Creating numpy arrays using numpy functions

In [18]:
import numpy as np

# Create arrays
arr1 = np.array([1,2,3,4])
arr2 = np.arange(5,10)
arr3 = np.zeros((2,3))
arr4 = np.ones((3,2))

print("Array1:", arr1)
print("Array2:", arr2)
print("Zeros Array:\n", arr3)
print("Ones Array:\n", arr4)

# Indexing
print("arr1[2]:", arr1[2])
print("arr2[1:4]:", arr2[1:4])

Array1: [1 2 3 4]
Array2: [5 6 7 8 9]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
arr1[2]: 3
arr2[1:4]: [6 7 8]


 Create a random array of 5 random numbers between 1 and 50 and display them. 

In [19]:
import numpy as np
# create a random array of integers between 1 and 50 with size 5
arr = np.random.randint(1, 50, size=5)
print("Random Array:", arr)


Random Array: [47 30 28 39 39]


Reshaping of Arrays using NumPy

 Reshape 1D array to 2D array

Write a Python program to reshape a 1D array into a 2D array using NumPy.


In [21]:
import numpy as np
# create 1D array of integers from 1 to 10
arr = np.arange(1, 11)
print("1D Array from 1 to 10:", arr)
# convert 1D array into 2D using reshape    
arr_2d = arr.reshape(2, 5)
print("Reshaped 2D Array:\n", arr_2d)

1D Array from 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]
Reshaped 2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


 Reshape 2D array to 1D array

Write a Python program to convert a 2D array into a 1D array using NumPy.

In [22]:
import numpy as np
# create a 2D array and reshape it into 1D
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

arr1d = arr2d.reshape(-1)
print("Original 2D Array:", arr2d)
print("Reshaped 1D Array:", arr1d)

Original 2D Array: [[1 2 3]
 [4 5 6]]
Reshaped 1D Array: [1 2 3 4 5 6]


Reshape 1D array to 3D array

Write a Python program to reshape a 1D array into a 3D array using NumPy.

In [23]:
import numpy as np
# craete a 1D array and reshape it into 3D
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr3d = arr1d.reshape(2, 2, 2)
print("Original 1D Array:", arr1d)
print("Reshaped 3D Array:", arr3d)


Original 1D Array: [1 2 3 4 5 6 7 8]
Reshaped 3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


 Reshape 2D array to 3D array

Write a Python program to reshape a 2D array into a 3D array using NumPy

In [24]:
import numpy as np
# Create a 2D array and reshape it into 3D
arr2d = np.array([[1, 2],
 [3, 4],
 [5, 6],
 [7, 8]])

arr3d = arr2d.reshape(2, 2, 2)
print("Original 2D Array:", arr2d)
print("Reshaped 3D Array:", arr3d)

Original 2D Array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Reshaped 3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stacking in NumPy

📌 Types of Stacking in NumPy

We mainly use:

vstack() → Vertical stacking,
 hstack() → Horizontal stacking,
  stack() → Add new dimension,
   dstack() → Depth stacking (3D)

In [25]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])

print("Original Arrays:")
print(a)
print(b)

# Vertical Stack
print("\nVertical Stack:")
print(np.vstack((a,b)))

# Horizontal Stack
print("\nHorizontal Stack:")
print(np.hstack((a,b)))

# Stack with new axis
print("\nStack axis=0:")
print(np.stack((a,b), axis=0))

print("\nStack axis=1:")
print(np.stack((a,b), axis=1))

# Depth stack
a2 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])

print("\nDepth Stack:")
print(np.dstack((a2,b2)))

Original Arrays:
[1 2]
[3 4]

Vertical Stack:
[[1 2]
 [3 4]]

Horizontal Stack:
[1 2 3 4]

Stack axis=0:
[[1 2]
 [3 4]]

Stack axis=1:
[[1 3]
 [2 4]]

Depth Stack:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Broadcasting

What is Broadcasting?

👉 Broadcasting = performing operations on arrays of different shapes

Instead of manually matching sizes, NumPy automatically expands arrays.

In [26]:
import numpy as np

# Example 1: Scalar
arr = np.array([1,2,3])
print("Scalar + Array:", arr + 5)

# Example 2: Row broadcasting
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([10,20,30])
print("\nRow Broadcasting:\n", a + b)

# Example 3: Column broadcasting
c = np.array([[1],[2],[3]])
d = np.array([10,20,30])
print("\nColumn Broadcasting:\n", c + d)

Scalar + Array: [6 7 8]

Row Broadcasting:
 [[11 22 33]
 [14 25 36]]

Column Broadcasting:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
